# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.CharField(max_length=30)),
                ('healthier_ID', models.CharField(max_length=30)),
                ('service_ID', models.CharField(max_length=30)),
                ('pickup_date', models.CharField(max_length=30)),
                ('pickup_address', models.CharField(max_length=30)),
                ('pickup_city', models.CharField(max_length=30)),
                ('destination_address', models.CharField(max_length=30)),
                ('destination_city', models.CharField(max_length=200)),
                ('destination_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('sub_group', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('cost_denom', models.CharField(max_length=200)),
                ('service_ID', models.CharField(max_length=30)),
                ('days_available', models.CharField(max_length=200)),
                ('time_available', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthier_ID', models.CharField(max_length=30)),
                ('service_date', models.CharField(max_length=200)),
                ('health_data', models.CharField(max_length=200)),
                ('data_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthier_ID', models.CharField(max_length=30)),
                ('service_ID', models.CharField(max_length=30)),
                ('payment_status', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=30)),
                ('order_ID', models.CharField(max_length=30)),
                ('preferred_date', models.CharField(max_length=200)),
                ('preferred_time', models.CharField(max_length=200)),
                ('promo_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=30)),
                ('pro_logo', models.ImageField(upload_to=None)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('provider_ID', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=200)),
                ('provider_ratings', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('order_ID', models.CharField(max_length=30)),
                ('service_date', models.CharField(max_length=30)),
                ('service_time', models.CharField(max_length=30)),
                ('name_staff', models.CharField(max_length=50)),
                ('presenting_complaints', models.TextField(max_length=30)),
                ('exam_report', models.TextField(max_length=30)),
                ('treatment_plan', models.TextField(max_length=30)),
                ('vaccine_expirydate', models.CharField(max_length=200)),
                ('vaccine_batchnumber', models.CharField(max_length=200)),
                ('next_appointment', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=30)),
                ('order_ID', models.CharField(max_length=30)),
                ('service_date', models.CharField(max_length=200)),
                ('service_time', models.CharField(max_length=200)),
                ('attending_staff', models.CharField(max_length=200)),
                ('presenting_complaints', models.CharField(max_length=30)),
                ('exam_findings', models.CharField(max_length=30)),
                ('treatment_plan', models.CharField(max_length=30)),
                ('vaccine_expiry', models.CharField(max_length=30)),
                ('vaccine_batch', models.CharField(max_length=30)),
                ('next_appointment', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthier_ID', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=200)),
                ('date_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('', 'Select Gender'), ('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('text', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
