# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_group', models.CharField(max_length=50)),
                ('service_subgroup', models.CharField(max_length=30)),
                ('service_name', models.CharField(max_length=30)),
            ],
        ),
    ]
