# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0002_servicegroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicegroup',
            old_name='service_group',
            new_name='servicegroup',
        ),
        migrations.RenameField(
            model_name='servicegroup',
            old_name='service_name',
            new_name='servicename',
        ),
        migrations.RenameField(
            model_name='servicegroup',
            old_name='service_subgroup',
            new_name='servicesubgroup',
        ),
        migrations.AddField(
            model_name='healthservice',
            name='providers',
            field=models.ManyToManyField(to='new_project.ProviderProfile'),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='cost',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='cost_denom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='days_available',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='time_available',
            field=models.CharField(max_length=100),
        ),
    ]
