# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0003_auto_20170808_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthier_ID', models.CharField(max_length=30)),
                ('provider_ID', models.CharField(max_length=30)),
                ('org_name', models.CharField(max_length=30)),
                ('provider_ratings', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='servicegroup',
            old_name='servicegroup',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='servicegroup',
            old_name='servicesubgroup',
            new_name='Group',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='provider_ratings',
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('', 'Payment Status'), ('P', 'Paid'), ('NP', 'Not Paid')], max_length=30),
        ),
    ]
