# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0004_auto_20170809_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthier_ID', models.CharField(max_length=30)),
                ('order_ID', models.CharField(max_length=30)),
                ('service_date', models.CharField(max_length=30)),
                ('service_test', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('lower_range', models.CharField(max_length=30)),
                ('upper_range', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='sentreport',
            old_name='exam_report',
            new_name='exam_findings',
        ),
    ]
