# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0005_auto_20170809_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthier_ID', models.CharField(max_length=200)),
                ('request_date', models.CharField(max_length=200)),
                ('request_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=30)),
                ('rate', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='TestReport',
        ),
    ]
