# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0007_auto_20170810_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthservice',
            name='service_name',
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='sub_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.ServiceGroup'),
        ),
    ]
