# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0008_auto_20170811_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicegroup',
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AddField(
            model_name='healthservice',
            name='Category',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthservice',
            name='Service',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
