# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0009_auto_20170811_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentreport',
            name='healthier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulreport',
            name='healthier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.UserProfile'),
        ),
        migrations.AlterField(
            model_name='ambulreport',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.OrderedService'),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='Category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='Service',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='measuredtest',
            name='healthier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.UserProfile'),
        ),
        migrations.AlterField(
            model_name='measuredtest',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.OrderedService'),
        ),
        migrations.AlterField(
            model_name='myhealth',
            name='healthier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.UserProfile'),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='healthier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.UserProfile'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='healthier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.UserProfile'),
        ),
        migrations.AlterField(
            model_name='sentreport',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_project.OrderedService'),
        ),
    ]
