# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0010_auto_20170811_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='ProviderProfile',
            new_name='Provider',
        ),
        migrations.AddField(
            model_name='orderedservice',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='promo_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sentreport',
            name='next_appointment',
            field=models.DateField(),
        ),
    ]
