# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_project', '0013_auto_20170814_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='providerrating',
            name='org_name',
        ),
        migrations.RemoveField(
            model_name='providerrating',
            name='provider_ID',
        ),
        migrations.RemoveField(
            model_name='providerrating',
            name='provider_ratings',
        ),
        migrations.AddField(
            model_name='provider',
            name='portal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='provider_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='provider_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_project.Provider'),
        ),
    ]
