# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0014_auto_20170816_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_pix',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('', 'Payment Status'), ('Paid', 'P'), ('Not Paid', 'NP')], max_length=30),
        ),
    ]
