# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0015_auto_20170817_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedservice',
            old_name='service_ID',
            new_name='serv_ordered',
        ),
        migrations.AddField(
            model_name='orderedservice',
            name='serv_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_project.Provider'),
        ),
    ]
