# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0016_auto_20170817_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentreport',
            name='file_upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='category_ID',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='group_ID',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RemoveField(
            model_name='providerrating',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='providerrating',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='providerrating',
            name='healthier_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_project.Customer'),
        ),
        migrations.RemoveField(
            model_name='providerrating',
            name='likes',
        ),
        migrations.AddField(
            model_name='providerrating',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
