# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0017_auto_20170821_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentreport',
            old_name='healthier_ID',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='sentreport',
            name='exam_findings',
        ),
        migrations.AddField(
            model_name='sentreport',
            name='general_findings',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='providerrating',
            name='healthier_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_rating', to='new_project.Customer'),
        ),
    ]
