# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0018_auto_20170823_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulreport',
            old_name='healthier_ID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ambulreport',
            old_name='order_ID',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='ambulreport',
            old_name='service_ID',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='healthier_ID',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='healthservice',
            old_name='provider_ID',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='measuredtest',
            old_name='healthier_ID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='measuredtest',
            old_name='order_ID',
            new_name='ordered_service',
        ),
        migrations.RenameField(
            model_name='myhealth',
            old_name='healthier_ID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderedservice',
            old_name='healthier_ID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='providerrating',
            old_name='healthier_ID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='healthier_ID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sentreport',
            old_name='order_ID',
            new_name='ordered_service',
        ),
        migrations.RenameField(
            model_name='servicegroup',
            old_name='category_ID',
            new_name='category_code',
        ),
        migrations.RenameField(
            model_name='servicegroup',
            old_name='group_ID',
            new_name='group_code',
        ),
        migrations.RemoveField(
            model_name='healthservice',
            name='service_ID',
        ),
        migrations.RemoveField(
            model_name='orderedservice',
            name='order_ID',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='provider_ID',
        ),
    ]
