# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0020_auto_20170825_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhealth',
            name='health_data',
            field=models.CharField(choices=[('Systolic Blood Pressure', 'Systolic Blood Pressure'), ('Diastolic Blood Pressure', 'Diastolic Blood Pressure'), ('Random Blood Sugar', 'Random Blood Sugar'), ('Fasting Blood Sugar', 'Fasting Blood Sugar'), ('Weight', 'Weight'), ('Cholseterol', 'Cholseterol'), ('Current Drugs', 'Current Drugs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='pro_logo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='duration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='requests',
            name='rate',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
