# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0021_auto_20170901_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_project.Provider'),
        ),
    ]
