# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0022_requests_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredtest',
            name='name_staff',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sentreport',
            name='service_prov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_project.Provider'),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='serv_provider',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
